### ISSUE TITLE
Stopwatch is always on top of other windows

### ISSUE THREAD

**Issue by SimonBL** [SilverAzide/Stopwatch#2]
Hi SilverAzide and thanks for your add-on. It works good however, it's always on top of other windows when active. This may be by design but since I like having it active all the time, it would be nice to have the option to have it stay on desktop level. Thanks.

**Comment by SilverAzide** [comment]
Hello!  Glad you like Gadgets!
The Stopwatch defaults to being on top by design, so that it won't get covered up by another window and prevent you from being able to stop it.

However, this is only the initial default.  If you want to change this behavior, all you need to do is right-click the skin, and from the context menu select Settings > Position > Normal (or whatever you prefer).  This is a Rainmeter function that applies to all Rainmeter skins, not just this one.

Hope this helps!
